# Configuração do Prettier para o projeto TwBus
# Garante formatação consistente do código

# Configurações básicas
semi: true
singleQuote: true
tabWidth: 2
useTabs: false
trailingComma: 'none'
printWidth: 100
bracketSpacing: true
arrowParens: 'avoid'
endOfLine: 'lf'

# Configurações específicas para diferentes tipos de arquivo
overrides:
  - files: '*.json'
    options:
      tabWidth: 2
      singleQuote: false
  
  - files: '*.md'
    options:
      printWidth: 80
      proseWrap: 'always'
  
  - files: '*.css'
    options:
      singleQuote: false
      tabWidth: 2
  
  - files: '*.html'
    options:
      htmlWhitespaceSensitivity: 'ignore'
      printWidth: 120
